---
    - name: restart nginx
      action: service name=nginx state=restarted
      notify: nginx restarted
    - name: restart nginx
      action: service name=redis-server state=restarted
      notify: redis-server restarted
    - name: stop apache2
      action: service name=apache2 state=stopped
      notify: stopped apache2
